AelfScanProject/aelfscan-web

src/_utils/contant.ts, src/_utils/formatter.ts, src/_utils/urlUtils.ts, src/app/[chain]/nft/[collectionSymbol]/_Detail/_inventory/CardList.tsx, src/app/[chain]/nft/[collectionSymbol]/_Detail/type.ts
=> feat: adjust inventory field

src/_components/AddressDetail/index.tsx, src/app/[chain]/address/columnConfig.tsx, src/app/[chain]/nft/[collectionSymbol]/[itemSymbol]/_itemActivity/ItemActivityTable.tsx, src/app/[chain]/nft/[collectionSymbol]/[itemSymbol]/_itemActivity/column.tsx, src/app/[chain]/nft/[collectionSymbol]/_Detail/_overview/OverView.tsx
=> feat: change nft floorPrice

src/_api/fetchTokens.ts, src/_api/fetchTransactions.ts, src/_api/server.ts, src/_api/type.ts, src/_components/IconFont/index.tsx, src/_components/PageLoadingSkeleton/index.tsx, src/_hooks/useHomeSocket.ts, src/_socket/signalr.ts, src/_utils/formatter.ts, src/app/[chain]/address/[address]/[addressType]/loading.tsx, src/app/[chain]/address/loading.tsx, src/app/[chain]/block/[hash]/loading.tsx, src/app/[chain]/blocks/loading.tsx, src/app/[chain]/contracts/loading.tsx, src/app/[chain]/loading.tsx, src/app/[chain]/nft/[collectionSymbol]/loading.tsx, src/app/[chain]/nfts/loading.tsx, src/app/[chain]/token/[tokenSymbol]/loading.tsx, src/app/[chain]/tokens/loading.tsx, src/app/[chain]/transactions/loading.tsx, src/app/[chain]/tx/[hash]/loading.tsx, src/app/loading.tsx, src/pageComponents/home/_components/InfoSection/index.css, src/pageComponents/home/_components/InfoSection/index.tsx, src/pageComponents/home/_components/Latest/index.tsx, src/pageComponents/home/page.tsx
=> feat: add home blockChainOverview

src/_api/fetchBlocks.ts, src/_components/ContractToken/index.tsx, src/_utils/formatter.ts, src/app/[chain]/block/[hash]/_components/baseinfo.tsx, src/app/[chain]/nft/[collectionSymbol]/[itemSymbol]/_itemActivity/column.tsx, src/app/[chain]/nft/[collectionSymbol]/[itemSymbol]/_overview/OverView.tsx, src/app/[chain]/nft/[collectionSymbol]/[itemSymbol]/_overview/OverViewDetail.tsx, src/app/[chain]/nft/[collectionSymbol]/_Detail/_inventory/CardList.tsx, src/app/[chain]/nft/[collectionSymbol]/_Detail/_inventory/Inventory.tsx, src/app/[chain]/nft/[collectionSymbol]/_Detail/_overview/OverView.tsx, src/app/[chain]/tx/[hash]/_components/baseInfo.tsx, src/app/[chain]/tx/[hash]/_components/detail.tsx, src/app/[chain]/tx/[hash]/page.tsx
fixed collection details page error and interface error handling
=> fix: fixed collection details page error and interface error handling

src/_components/AddressDetail/components/History/index.tsx, src/_components/ChainSelect/index.tsx, src/_components/ContractToken/index.tsx, src/_components/HeaderMenu/index.tsx, src/_components/HeaderTop/index.tsx, src/_components/Market/index.tsx, src/_components/MobileHeaderMenu/index.tsx, src/_socket/index.ts, src/_types/index.ts, src/app/[chain]/nft/[collectionSymbol]/[itemSymbol]/NFTDetails.tsx, src/app/[chain]/nft/[collectionSymbol]/[itemSymbol]/_holders/HoldersTable.tsx, src/app/[chain]/nft/[collectionSymbol]/[itemSymbol]/_itemActivity/ItemActivityTable.tsx, src/app/[chain]/nft/[collectionSymbol]/[itemSymbol]/_itemActivity/column.tsx, src/app/[chain]/nft/[collectionSymbol]/[itemSymbol]/_overview/OverViewDetail.tsx, src/app/[chain]/tokens/tokensList.tsx
=> fix: fix contract address display

src/_components/Header/index.tsx, src/_components/HeaderMenu/index.tsx, src/_components/HeaderTop/index.tsx, src/_components/MobileHeaderMenu/index.tsx, src/_components/TokenTransfers/columnConfig.tsx, src/_socket/index.ts, src/_types/commonDetail.ts, src/app/[chain]/tx/[hash]/page.tsx
1. menu Select the status and transfers picture to show
=> menu Select the status and transfers picture to show

src/_components/AddressDetail/components/Events/columnConfig.tsx, src/_components/AddressDetail/components/Events/mock.ts, src/_components/ChainSelect/index.tsx, src/_components/LogsContainer/index.tsx, src/_components/LogsContainer/logItems.tsx, src/_components/LogsContainer/type.ts, src/_utils/deserializeLog.ts, src/app/[chain]/nft/[collectionSymbol]/[itemSymbol]/_overview/OverView.tsx, src/app/[chain]/tx/[hash]/_components/baseInfo.tsx, src/app/layout.tsx, src/app/pageProvider.tsx
1. nft item detail Collection Name Add jump
2. transactionsLog decode
=> feat: transactionsLog decode

src/_components/Header/index.tsx, src/_components/HeaderTop/index.tsx, src/_hooks/useBlockchainOverview.ts, src/_hooks/useHomeSocket.ts, src/pageComponents/home/_components/InfoSection/index.tsx, src/pageComponents/home/page.tsx
1. token price uses Coingeko data and CMC as an alternative, and is refreshed every 5 minutes
2. Price Change Rate: Compares the price (X) at the current update point with the price (Y) within 24 hours of the current update point. The calculation rule is (x-y) ÷ y-1 (unit: %)
=> feat: header Price display

.github/workflows/deploy-testnet.yaml, src/_api/type.ts, src/_components/Table/index.tsx, src/app/[chain]/blocks/blockList.tsx
=> blocks add isLastPage

src/_components/ContractToken/index.tsx, src/app/not-found.tsx
=> feat: fix contract name jump link

src/_components/ContractToken/index.tsx, src/app/not-found.tsx
=> adjust contract jump

src/_components/DetailContainer/index.tsx, src/app/[chain]/tx/[hash]/_components/baseInfo.tsx
=> feat: adjust transaction detail

src/_components/HeaderMenu/index.tsx, src/_style/globals.css, src/app/[chain]/tx/[hash]/_components/baseInfo.tsx, tailwind.config.js
=> feat: adjust  color

src/_components/DetailContainer/index.tsx, src/_components/HeaderMenu/index.tsx, src/_style/globals.css, src/app/[chain]/tx/[hash]/_components/baseInfo.tsx, tailwind.config.js
=> adjust color

src/_components/DetailContainer/index.tsx, src/_components/DollarCurrencyRate/index.tsx, src/_components/EPTabs/index.css, src/_components/Footer/index.tsx, src/_components/Header/index.tsx, src/_components/HeaderTop/index.tsx, src/_components/Main/index.css, src/_hooks/useResponsive.ts, src/_socket/index.ts, src/_style/search.css, src/app/[chain]/tx/[hash]/_components/ExtensionInfo.tsx, src/app/[chain]/tx/[hash]/_components/baseInfo.tsx, src/pageComponents/home/_components/InfoSection/index.css, src/pageComponents/home/_components/InfoSection/index.tsx, src/pageComponents/home/_components/Latest/index.css, src/pageComponents/home/_components/Latest/index.tsx, src/pageComponents/home/index.css, src/pageComponents/home/page.tsx, tailwind.config.js
adjust home and tx detail style
=> feat:  adjust home and tx detail style

src/_components/DetailContainer/index.tsx, src/_components/IconFont/index.tsx, src/_components/MoreContainer/index.tsx, src/_socket/index.ts, src/app/[chain]/tx/[hash]/_components/baseInfo.tsx, src/app/[chain]/tx/[hash]/_components/detail.tsx, src/pageComponents/home/_components/InfoSection/index.css, src/pageComponents/home/_components/Latest/index.css, src/pageComponents/home/_components/Latest/index.tsx, src/pageComponents/home/_components/TPSChart/index.css
=> feat: home and tx detail style

src/_hooks/useResponsive.ts, src/pageComponents/home/_components/Latest/index.tsx
=> feat: adjust mobile style

src/pageComponents/home/_components/Latest/index.tsx
=> feat: home producer style

src/_hooks/useResponsive.ts, src/pageComponents/home/_components/Latest/index.tsx
=> home producer style

src/_hooks/useUpdateQueryParams.ts, src/app/pluginsPage/page.tsx, src/middleware.ts
=> feat: fix page reload

src/_hooks/useUpdateQueryParams.ts, src/app/pluginsPage/page.tsx, src/middleware.ts
=> fix page reload

src/pageComponents/home/_components/Latest/index.css
=> feat: fix home latest blocks style

src/_components/AddressDetail/components/DynamicForm/formItem.tsx, src/_components/AddressDetail/components/DynamicForm/valueFormItem.tsx
=> feat: adjust input event

src/_components/AddressDetail/components/DynamicForm/formItem.tsx, src/_components/AddressDetail/components/DynamicForm/index.css, src/_components/AddressDetail/components/DynamicForm/index.tsx
=> feat: fix mobile style

src/_components/AddressDetail/components/DynamicForm/formItem.tsx, src/_components/AddressDetail/components/DynamicForm/index.css, src/_components/AddressDetail/components/DynamicForm/index.tsx, src/_components/AddressDetail/components/DynamicForm/valueFormItem.tsx
=> fix mobile style

src/_components/HeaderTop/index.css, src/_components/HeaderTop/index.tsx, src/_components/MobileHeaderMenu/index.tsx
=> feat: add network switch

src/app/[chain]/chart/dailyAddAddress/page.tsx
=> feat: change dailyAddress chart y

src/_components/Header/index.tsx, src/_components/HeaderMenu/index.tsx, src/_components/MobileHeaderMenu/index.tsx
fix header jump did not record route history
=> fix: fix header jump did not record route history

src/_components/HeaderMenu/index.tsx, src/_components/MobileHeaderMenu/index.tsx
optimized the header jump mode close #133
=> feat: optimized the header jump mode

src/_socket/index.ts
=> feat: change socket api

src/_api/fetchChart.ts, src/_api/list.ts, src/app/[chain]/chart/_components/charts.tsx, src/app/[chain]/chart/_components/highlight.tsx, src/app/[chain]/chart/active-address/page.tsx, src/app/[chain]/chart/address/page.tsx, src/app/[chain]/chart/avg-duration/page.tsx, src/app/[chain]/chart/avg-txfee/page.tsx, src/app/[chain]/chart/blocksize/page.tsx, src/app/[chain]/chart/burnt/page.tsx, src/app/[chain]/chart/contract-calls/page.tsx, src/app/[chain]/chart/cycle-count/page.tsx, src/app/[chain]/chart/deployed-contracts/page.tsx, src/app/[chain]/chart/holders/page.tsx, src/app/[chain]/chart/marketcap/page.tsx, src/app/[chain]/chart/page.tsx, src/app/[chain]/chart/price/page.tsx, src/app/[chain]/chart/production-rate/page.tsx, src/app/[chain]/chart/rewards/page.tsx, src/app/[chain]/chart/staked/page.tsx, src/app/[chain]/chart/supply-growth/page.tsx, src/app/[chain]/chart/transactions/page.tsx, src/app/[chain]/chart/txfee/page.tsx, src/app/[chain]/chart/type.ts
=> feat: holders

.sentryclirc, build.config/plugin.js, next.config.js, package.json, sentry.client.config.ts, sentry.config.ts, sentry.edge.config.ts, sentry.server.config.ts, src/_api/fetchChart.ts, src/_api/list.ts, src/_components/AddressDetail/index.tsx, src/_components/Search/SearchBox.tsx, src/_components/charts/mock.ts, src/_hooks/useSearch.ts, src/_socket/index.ts, src/app/[chain]/chart/page.tsx, src/app/[chain]/chart/tvl/page.tsx, src/app/[chain]/chart/type.ts, src/app/error.tsx, yarn.lock
=> feat: chart and sentry

src/_components/DetailContainer/index.tsx, src/_utils/deserializeLog.ts, src/app/[chain]/block/[hash]/_components/baseinfo.tsx, src/app/[chain]/block/[hash]/_components/detail.tsx, src/app/[chain]/block/[hash]/layout.tsx, src/app/[chain]/block/[hash]/loading.tsx, src/app/[chain]/block/[hash]/page.tsx
=> feat: block detail optimize

src/app/[chain]/chart/supply-growth/page.tsx, src/app/[chain]/chart/type.ts, src/pageComponents/home/_components/Latest/index.tsx
=> feat: supply add organizationUnlock

src/_components/Search/Item.tsx, src/_components/Search/Panel.tsx
=> fix: fix home search accounts link

src/_components/Search/Item.tsx, src/_components/Search/Panel.tsx, src/app/[chain]/chart/supply-growth/page.tsx
organizationUnlock value error repair
=> organizationUnlock value error repair

src/app/[chain]/chart/type.ts
=> feat: chart colors

next.config.js, package.json, src/app/opentelemetryProvider.tsx, src/app/pageProvider.tsx, yarn.lock
=> feat: add Opentelemetry

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/config.yml, .github/ISSUE_TEMPLATE/feature_request.md
change request and issue template
=> feat: change request and issue template

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/config.yml, .github/ISSUE_TEMPLATE/feature_request.md, next.config.js, src/_plugins/nft/CollectionDetails.js
fix nft holders display as inventory
=>  fix nft holders display as inventory

src/_components/PageAd/index.tsx, src/_socket/index.ts, src/app/[chain]/chart/_components/charts.tsx, src/app/[chain]/chart/active-address/page.tsx, src/app/[chain]/chart/address/page.tsx, src/app/[chain]/chart/avg-duration/page.tsx, src/app/[chain]/chart/avg-txfee/page.tsx, src/app/[chain]/chart/blocksize/page.tsx, src/app/[chain]/chart/burnt/page.tsx, src/app/[chain]/chart/contract-calls/page.tsx, src/app/[chain]/chart/cycle-count/page.tsx, src/app/[chain]/chart/deployed-contracts/page.tsx, src/app/[chain]/chart/holders/page.tsx, src/app/[chain]/chart/marketcap/page.tsx, src/app/[chain]/chart/price/page.tsx, src/app/[chain]/chart/produce/page.tsx, src/app/[chain]/chart/production-rate/page.tsx, src/app/[chain]/chart/rewards/page.tsx, src/app/[chain]/chart/staked/page.tsx, src/app/[chain]/chart/supply-growth/page.tsx, src/app/[chain]/chart/transactions/page.tsx, src/app/[chain]/chart/tvl/page.tsx, src/app/[chain]/chart/txfee/page.tsx
=> feat: ads style change

package.json, src/_api/fetchSearch.ts, src/_utils/formatter.ts, yarn.lock
=> feat: ads headers add  SearchKey

src/app/[chain]/chart/active-address/page.tsx
fix active-address chart sendAddressCount
=> fix: fix active-address chart sendAddressCount

src/_components/Search/Panel.tsx, src/_components/Search/SearchBox.tsx
fix homeSearch transactions search-result
=> fix: fix homeSearch transactions search-result

src/app/pageProvider.tsx
=> feat: opentelemetry

src/_components/Search/Panel.tsx
=> feat: search add loading

src/_components/Search/SearchBox.tsx
=> fix: fix search jump

src/_components/Search/SearchBox.tsx, src/_components/Search/reducer.ts
=> fix: fix no search

src/_components/Search/Panel.tsx, src/_components/Search/SearchBox.tsx, src/_hooks/useSearch.ts
=> fix: fix search

src/_components/AddressDetail/index.tsx, src/app/[chain]/chart/produce/page.tsx, src/app/[chain]/token/[tokenSymbol]/_components/Overview/index.tsx, src/app/[chain]/token/[tokenSymbol]/_components/Transfers/index.tsx, src/app/[chain]/tx/[hash]/_components/baseInfo.tsx, src/app/pageProvider.tsx
fix 1.6.2 Problem optimization
=> fix: fix 1.6.2 Problem optimization

src/app/pageProvider.tsx
=> fix: fix network error

src/_components/ContractToken/index.tsx, src/_components/HeaderTop/index.tsx, src/app/layout.tsx, src/app/opentelemetryProvider.tsx, src/pageComponents/home/_components/Latest/index.tsx
=> fix: fix home prefetch

src/app/pageProvider.tsx
=> fix: fix opentelemetry

next.config.js, src/_components/ChainSelect/index.tsx, src/_plugins/nft/_inventory/CardList.js, src/app/opentelemetryProvider.tsx, src/app/pageProvider.tsx
=> fix: fix nfts Inventory link

src/app/opentelemetryProvider.tsx
=> fix: fix Opentelemetry prefix

src/_components/AddressDetail/components/Contract/index.tsx
change contract read method api
=> feat: change contract read method api

src/app/[chain]/tx/[hash]/_components/baseInfo.tsx, src/app/[chain]/tx/[hash]/_components/detail.tsx
=> fix: fix tx detail logs

src/_api/type.ts, src/_utils/formatter.ts, src/app/[chain]/address/list.tsx, src/app/[chain]/address/page.tsx, src/app/[chain]/blocks/page.tsx, src/app/[chain]/contracts/page.tsx, src/app/[chain]/nfts/page.tsx, src/app/[chain]/transactions/list.tsx
=> feat: account list search after

src/_components/PageAd/index.tsx, src/_components/Search/SearchBox.tsx
=> fix: fix ads exposure

src/_api/type.ts, src/_components/AddressDetail/index.tsx, src/_utils/formatter.ts, src/app/[chain]/transactions/list.tsx, src/app/[chain]/transactions/page.tsx
transaction list add search after
=> feat: transaction list add search after

src/app/pageProvider.tsx, src/pageComponents/home/_components/InfoSection/index.css
=> fix: fix search box style

src/pageComponents/home/_components/TPSChart/index.tsx, src/pageComponents/home/page.tsx
=> fix: fix chart loading

src/app/[chain]/block/[hash]/_components/detail.tsx
=> fix: fix block detail type error

src/_plugins/nft/CollectionDetails.js, src/_plugins/nft/_holders/HoldersTable.js, src/_plugins/nft/_inventory/Inventory.js, src/_plugins/nft/_transfers/Table.js, src/app/[chain]/chart/marketcap/page.tsx
=> feat: nfts detail search optimized

src/_api/type.ts, src/_components/AddressDetail/components/Events/columnConfig.tsx, src/_components/AddressDetail/components/History/index.tsx, src/_components/AddressDetail/index.tsx, src/_components/Search/Item.tsx, src/_components/Search/SearchBox.tsx, src/_components/TokenTransfers/columnConfig.tsx, src/_components/TransactionsView/index.tsx, src/_plugins/nft/_inventory/CardList.js, src/_plugins/nft/_transfers/column.js, src/_plugins/nftItem/_itemActivity/column.js, src/app/[chain]/layout.tsx, src/app/[chain]/loading.tsx, src/app/[chain]/token/[tokenSymbol]/_components/Transfers/columns.tsx, src/app/[chain]/token/[tokenSymbol]/_components/Transfers/utils.tsx, src/app/[chain]/token/[tokenSymbol]/detail.tsx, src/app/[chain]/transactions/columnConfig.tsx, src/app/[chain]/tx/[hash]/page.tsx, src/pageComponents/home/_components/Latest/index.tsx
tx details do not require blockHeight
=> feat: tx details do not require blockHeight

src/_components/TokenTransfers/index.tsx, src/app/[chain]/blocks/blockList.tsx, src/app/[chain]/chart/produce/list.tsx, src/app/[chain]/contracts/contractsList.tsx, src/app/[chain]/nfts/list.tsx, src/app/[chain]/tokens/tokensList.tsx
=> fix: fix route page error

src/app/[chain]/chart/deployed-contracts/page.tsx
deployed contracts del  dailyIncrease
=> fix: deployed contracts del  dailyIncrease

src/_components/Footer/index.tsx
=> feat: footer style change

src/_components/Footer/index.tsx
footer style optimization and copy modification
=> footer style optimization and copy modification

src/_components/AddressDetail/components/DynamicForm/index.css, src/_components/AddressDetail/components/DynamicForm/index.tsx, src/_components/IconFont/index.tsx, src/_hooks/useSearch.ts, src/app/webLoginProvider.tsx
=> feat: contract detail add logout

src/_api/fetchSearch.ts, src/_api/list.ts, src/_api/type.ts, src/_components/AddressDetail/index.tsx, src/_components/AdsImage/index.tsx, src/_components/PageAd/index.tsx, src/_components/Search/SearchBox.tsx, src/app/[chain]/tx/[hash]/_components/baseInfo.tsx, src/pageComponents/home/_components/SearchWithClient/index.tsx, src/pageComponents/home/index.css, src/pageComponents/home/page.tsx
=> feat: banner ads

src/_components/AddressDetail/index.tsx, src/pageComponents/home/page.tsx
=> feat: ads style

sentry.config.ts, src/_components/AddressDetail/components/Contract/index.tsx, src/app/[chain]/chart/address/page.tsx, src/app/[chain]/chart/page.tsx, src/app/[chain]/chart/type.ts, src/app/[chain]/token/[tokenSymbol]/type.ts, src/app/[chain]/tokens/columnConfig.tsx
=> feat: unique address change

src/_components/Footer/index.tsx, src/_components/MobileHeaderMenu/index.css, src/_components/MobileHeaderMenu/index.tsx
=> feat: menu style

src/_components/AddressDetail/components/Events/columnConfig.tsx, src/_components/Footer/index.tsx, src/pageComponents/home/index.css, src/pageComponents/home/page.tsx
change events method  and header style
=> feat: change events method  and header style

next.config.js
=> feat: delete header no-cache

src/_components/TransactionsView/index.tsx
=> feat: transactionFeeList error

src/app/[chain]/tx/[hash]/_components/baseInfo.tsx
Transaction details transactionValue nowPrice is 0 and is not displayed
=> feat: Transaction details transactionValue nowPrice is 0 and is not displayed

src/_plugins/portkeyActivity/columnConfig.js
=> feat: hidden transaction value

src/app/pageProvider.tsx
=> feat: open Opentelemetry

next.config.js, sentry.config.ts, src/app/pageProvider.tsx
=> feat: add sentry replayIntegration

src/_components/AddressDetail/index.tsx, src/_plugins/portkeyActivity/index.js, src/app/pageProvider.tsx
=> feat: aatransactions

src/_api/fetchTransactions.ts, src/_api/list.ts, src/_components/AddressDetail/index.tsx, src/app/[chain]/transactions/aaList.tsx, src/app/[chain]/transactions/columnConfig.tsx
contract transaction support plugin
=> feat: contract transaction support plugin

package.json, src/_api/fetchTransactions.ts, src/_api/list.ts, src/app/[chain]/transactions/aaList.tsx, src/app/[chain]/transactions/list.tsx, yarn.lock
contract transaction Dynamically loads plug-in data
=> feat: contract transaction Dynamically loads plug-in data

src/_api/type.ts, src/_components/AddressDetail/index.tsx, src/_components/ChainSelect/index.css, src/_components/ChainSelect/multiCain.tsx, src/_components/ChainTags/index.tsx, src/_components/ContractToken/index.tsx, src/_components/Search/Item.tsx, src/_components/Search/SearchBox.tsx, src/_components/Search/type.ts, src/_components/Table/index.tsx, src/_hooks/useSelectChain.ts, src/_lib/AntdThemeConfig.ts, src/_utils/contant.ts, src/_utils/formatter.ts, src/_utils/urlUtils.ts, src/app/[chain]/address/columnConfig.tsx, src/app/[chain]/address/list.tsx, src/app/[chain]/address/page.tsx, src/app/[chain]/contracts/columnConfig.tsx, src/app/[chain]/contracts/contractsList.tsx, src/app/[chain]/contracts/page.tsx, src/app/[chain]/transactions/columnConfig.tsx, src/app/[chain]/transactions/list.tsx, src/app/[chain]/transactions/page.tsx
search accounts Data structure adjustment
=> feat: search accounts Data structure adjustment

src/app/[chain]/address/list.tsx, src/app/[chain]/transactions/columnConfig.tsx, src/app/[chain]/tx/[hash]/_components/baseInfo.tsx
=> feat: address

src/_components/Header/index.tsx, src/_pluginsComponents/nftItem/index.tsx
=> feat: fix build error

src/_api/type.ts, src/_hooks/useHomeSocket.ts, src/_store/features/chainIdSlice.ts, src/pageComponents/home/_components/Latest/index.tsx, src/pageComponents/home/_components/TPSChart/index.tsx, src/pageComponents/home/page.tsx
=> feat: top tokens and tps adjust

src/_components/AddressDetail/components/Contract/sourceCode.tsx, src/_components/AddressDetail/components/FileTree/index.tsx
=> fix: fix contract code

src/_components/AddressDetail/index.tsx, src/_components/Search/Item.tsx, src/_components/Search/Panel.tsx, src/_components/Search/SearchBox.tsx, src/_components/Search/type.ts, src/app/[chain]/contracts/columnConfig.tsx, src/app/layout.tsx
=> feat: search  add blocks

src/app/[chain]/blocks/blockList.tsx, src/app/[chain]/blocks/page.tsx
=> feat: blocks

src/pageComponents/home/page.tsx
=> feat: home Revise text

src/_api/type.ts, src/pageComponents/home/_components/Latest/index.tsx
top tokens name change to  tokenName
=> feat: top tokens name change to  tokenName

src/_api/server.ts, src/_components/AddressDetail/index.tsx, src/_components/HeaderTitle/index.tsx, src/_types/commonDetail.ts, src/_utils/formatter.ts
=> feat: account overview

src/_components/AddressDetail/components/Tokens/List/index.tsx, src/_components/AddressDetail/components/Tokens/NFTAssets/index.tsx, src/_components/AddressDetail/index.tsx, src/_components/NFTTransfers/index.tsx, src/_components/TokenTransfers/index.tsx
account detail interface modulation
=> feat: account detail interface modulation

src/_api/server.ts
=> feat: fix search loading

src/_api/type.ts, src/_components/Header/index.tsx, src/_components/HeaderTitle/index.tsx, src/_components/OverviewCard/three.tsx, src/_hooks/useSelectChain.ts, src/_pluginsComponents/nft/_holders/HoldersTable.tsx, src/_pluginsComponents/nft/_holders/column.tsx, src/_pluginsComponents/nft/_overview/OverView.tsx, src/_pluginsComponents/nft/_transfers/Table.tsx, src/_pluginsComponents/nft/_transfers/column.tsx, src/_pluginsComponents/nft/type.ts, src/app/[chain]/token/[tokenSymbol]/_components/Holders/index.tsx, src/app/[chain]/token/[tokenSymbol]/_components/Overview/index.tsx, src/app/[chain]/token/[tokenSymbol]/_components/Transfers/columns.tsx, src/app/[chain]/token/[tokenSymbol]/_components/Transfers/index.tsx, src/app/[chain]/token/[tokenSymbol]/detail.tsx, src/app/[chain]/token/[tokenSymbol]/page.tsx, src/app/[chain]/token/[tokenSymbol]/type.ts
=> feat: nft detail and token detail

src/pageComponents/home/_components/InfoSection/index.tsx, src/pageComponents/home/page.tsx
=> feat: multi hidden tps and tpm

src/pageComponents/home/_components/InfoSection/index.css, src/pageComponents/home/_components/InfoSection/index.tsx, src/pageComponents/home/_components/Latest/index.css, src/pageComponents/home/_components/Latest/index.tsx, src/pageComponents/home/page.tsx
=> feat: home title add tooltips

src/_components/AddressDetail/index.tsx
single account detail Multichain Info
=> feat: single account detail Multichain Info

src/_components/AddressDetail/index.tsx, src/_components/ChainSelect/index.tsx, src/_components/Header/index.tsx, src/_components/HeaderMenu/index.tsx, src/_components/HeaderTop/index.tsx, src/_components/MobileHeaderMenu/index.tsx, src/_components/OverviewCard/four.tsx, src/_components/OverviewCard/index.tsx, src/_components/OverviewCard/three.tsx, src/_pluginsComponents/nft/_overview/OverView.tsx, src/_pluginsComponents/nft/detail.css, src/_store/features/chainIdSlice.ts, src/_types/commonDetail.ts, src/_utils/contant.ts
=> feat: default select allChain

src/_api/type.ts, src/_pluginsComponents/nft/_overview/OverView.tsx, src/_pluginsComponents/nft/type.ts, src/app/[chain]/token/[tokenSymbol]/_components/Overview/index.tsx, src/app/[chain]/token/[tokenSymbol]/type.ts
nft and token detail change fields
=> feat: nft and token detail change fields

src/_pluginsComponents/nft/_overview/OverView.tsx, src/app/[chain]/token/[tokenSymbol]/_components/Overview/index.tsx, src/app/[chain]/transactions/page.tsx, src/app/[chain]/tx/[hash]/page.tsx
=> feat: fix transaction

src/_pluginsComponents/nft/_overview/OverView.tsx
=> feat: nft detail text change

src/_components/AddressDetail/index.tsx
=> feat: address detail

src/_components/NFTTransfers/index.tsx, src/_components/TokenTransfers/index.tsx, src/app/[chain]/token/[tokenSymbol]/_components/Transfers/index.tsx
=> feat: blocktime

src/_api/type.ts, src/_components/ChainSelect/index.tsx, src/_components/HeaderTitle/index.tsx, src/_components/MobileHeaderMenu/index.tsx, src/_pluginsComponents/nft/_inventory/CardList.tsx, src/_pluginsComponents/nft/_inventory/Inventory.tsx, src/_pluginsComponents/nft/_transfers/Table.tsx, src/_pluginsComponents/nft/index.tsx, src/_pluginsComponents/nft/type.ts
=> feat: fix nft chain switch

src/_utils/formatter.ts
=> feat: hidden formatDate Z

src/_components/NFTTransfers/index.tsx, src/_components/TokenTransfers/index.tsx, src/_pluginsComponents/nft/_transfers/Table.tsx, src/_utils/formatter.ts, src/app/[chain]/token/[tokenSymbol]/_components/Holders/columns.tsx, src/app/[chain]/token/[tokenSymbol]/_components/Transfers/index.tsx
transfer blockTime change to dateTime
=> feat: transfer blockTime change to dateTime

src/app/[chain]/address/list.tsx
change top account header text
=> feat: change top account header text

src/_components/BasicTag/index.tsx, src/_components/ChainTags/index.tsx, src/app/[chain]/transactions/aaList.tsx
=> feat: chainIds main in front

src/_components/BasicTag/index.tsx, src/_components/ChainTags/index.tsx
=> feat: fix home sort error

src/_pluginsComponents/nft/_overview/OverView.tsx, src/app/[chain]/tokens/columnConfig.tsx, src/pageComponents/home/_components/InfoSection/index.tsx
=> feat: nft style fix

src/app/[chain]/token/[tokenSymbol]/_components/Holders/index.tsx, src/app/[chain]/token/[tokenSymbol]/_components/Transfers/index.tsx
=> feat: token list text change

src/_components/AddressDetail/components/Tokens/NFTAssets/columnConfig.tsx, src/app/[chain]/transactions/columnConfig.tsx
=> feat: nftCollection detail

src/_api/server.ts, src/_api/type.ts, src/_components/AddressDetail/index.tsx, src/_components/ContractToken/index.tsx, src/_components/Search/Item.tsx, src/_components/Search/SearchBox.tsx, src/_pluginsComponents/nft/_inventory/CardList.tsx, src/_pluginsComponents/nft/_overview/OverView.tsx, src/_pluginsComponents/nftItem/NFTDetails.tsx, src/_pluginsComponents/nftItem/_holders/HoldersTable.tsx, src/_pluginsComponents/nftItem/_holders/column.tsx, src/_pluginsComponents/nftItem/_itemActivity/ItemActivityTable.tsx, src/_pluginsComponents/nftItem/_itemActivity/column.tsx, src/_pluginsComponents/nftItem/_overview/OverView.tsx, src/_pluginsComponents/nftItem/_overview/OverViewDetail.tsx, src/_pluginsComponents/nftItem/index.tsx, src/_pluginsComponents/nftItem/type.ts, src/_socket/index.ts, src/_utils/urlUtils.ts, src/app/[chain]/contracts/contractsList.tsx, src/app/[chain]/token/[tokenSymbol]/_components/Transfers/columns.tsx, src/app/[chain]/tokens/columnConfig.tsx, src/pageComponents/home/_components/InfoSection/index.tsx, src/pageComponents/home/_components/Latest/index.tsx
nft item detail  interface modulation
=> nft item detail 

src/_components/AddressDetail/components/Tokens/List/columnConfig.tsx, src/_types/commonDetail.ts
=> feat: account detail tokens

src/_socket/index.ts
=> feat: nft item detail

src/_components/Search/SearchBox.tsx, src/app/[chain]/search/[query]/page.tsx
=> fix: fix multi home search

src/app/[chain]/chart/blocksize/page.tsx, src/app/[chain]/chart/type.ts
=> feat: block size

src/app/[chain]/chart/avg-txfee/page.tsx, src/app/[chain]/chart/month-address/page.tsx, src/app/[chain]/chart/rewards/page.tsx
=> feat: multi chart adjust

src/_components/AddressDetail/components/Tokens/List/index.tsx, src/_components/AddressDetail/components/Tokens/NFTAssets/index.tsx, src/_components/AddressDetail/components/Tokens/index.tsx, src/_components/ChainSelect/index.tsx, src/_components/Table/index.tsx, src/app/layout.tsx
=> feat: nfts and assets style fix

src/_pluginsComponents/nftItem/NFTDetails.tsx, src/_pluginsComponents/nftItem/_holders/HoldersTable.tsx, src/_pluginsComponents/nftItem/_itemActivity/ItemActivityTable.tsx
=> fix: fix nft item tab

src/_pluginsComponents/nftItem/NFTDetails.tsx
=> fix: fix nft item

src/app/webLoginProvider.tsx
=> feat: test tg login

src/app/webLoginProvider.tsx
=> feat: login

src/_components/MobileHeaderMenu/index.tsx, src/_utils/contant.ts
=> feat: change tg jump link

src/_components/ChainSelect/index.tsx, src/_components/HeaderTop/index.tsx
=> fix: fix mobile default chain

src/_components/AddressDetail/components/DynamicForm/index.tsx
=> feat: tg hidden logout

package.json, src/_components/AddressDetail/components/DynamicForm/index.tsx, src/_components/ChainSelect/index.tsx, src/_components/HeaderTop/index.tsx, src/_components/MobileHeaderMenu/index.tsx, src/_utils/contant.ts, src/app/webLoginProvider.tsx, yarn.lock
tg applet automatically logs in. close #312
=> tg applet automatically logs in

src/app/[chain]/tx/[hash]/_components/baseInfo.tsx
transaction detail value show ELF
=> fix: transaction detail value show ELF

src/_components/AddressDetail/components/DynamicForm/index.tsx, src/pageComponents/home/_components/Latest/index.tsx
1. fix the transaction details for the value field description and value display. #315
2. add prefix and suffix to the latest transaction list addresses on the multi-chain homepage. #316
=> home Transactions add chian suffix

src/app/[chain]/chart/address/page.tsx
=> fix: fix address fields

src/app/[chain]/chart/address/page.tsx
to fix the display of the aelf Cumulative Addresses Chart data. close #319
=> fix address fields

src/_components/AddressDetail/components/Tokens/List/columnConfig.tsx, src/_components/AddressDetail/components/Tokens/NFTAssets/columnConfig.tsx, src/_components/TokenTransfers/columnConfig.tsx, src/_pluginsComponents/nft/_holders/column.tsx, src/_pluginsComponents/nft/_transfers/column.tsx, src/_pluginsComponents/nftItem/_holders/column.tsx, src/_pluginsComponents/nftItem/_itemActivity/column.tsx, src/app/[chain]/address/columnConfig.tsx, src/app/[chain]/blocks/blockList.tsx, src/app/[chain]/blocks/columnConfig.tsx, src/app/[chain]/chart/cycle-count/page.tsx, src/app/[chain]/chart/price/page.tsx, src/app/[chain]/contracts/columnConfig.tsx, src/app/[chain]/nfts/columnConfig.tsx, src/app/[chain]/token/[tokenSymbol]/_components/Holders/columns.tsx, src/app/[chain]/token/[tokenSymbol]/_components/Transfers/columns.tsx, src/app/[chain]/tokens/columnConfig.tsx, src/app/[chain]/transactions/columnConfig.tsx
sonarqube Code duplication rate optimization
=> feat: sonarqube Code duplication rate optimization

src/_hooks/useFetchChartData.ts, src/_hooks/usePagination.ts, src/app/[chain]/blocks/blockList.tsx, src/app/[chain]/chart/active-address/page.tsx, src/app/[chain]/chart/address/page.tsx, src/app/[chain]/chart/avg-duration/page.tsx, src/app/[chain]/chart/avg-txfee/page.tsx, src/app/[chain]/chart/blocksize/page.tsx, src/app/[chain]/chart/burnt/page.tsx, src/app/[chain]/chart/contract-calls/page.tsx, src/app/[chain]/chart/cycle-count/page.tsx, src/app/[chain]/chart/deployed-contracts/page.tsx, src/app/[chain]/chart/holders/page.tsx, src/app/[chain]/chart/marketcap/page.tsx, src/app/[chain]/chart/month-address/page.tsx, src/app/[chain]/chart/price/page.tsx, src/app/[chain]/chart/production-rate/page.tsx, src/app/[chain]/chart/rewards/page.tsx, src/app/[chain]/chart/staked/page.tsx, src/app/[chain]/chart/supply-growth/page.tsx, src/app/[chain]/chart/transactions/page.tsx, src/app/[chain]/chart/tvl/page.tsx, src/app/[chain]/chart/txfee/page.tsx, src/app/[chain]/contracts/contractsList.tsx
chart Code duplication rate optimization
=> feat: chart Code duplication rate optimization

src/_utils/formatter.ts, src/app/[chain]/chart/active-address/page.tsx, src/app/[chain]/chart/address/page.tsx, src/app/[chain]/chart/avg-duration/page.tsx, src/app/[chain]/chart/avg-txfee/page.tsx, src/app/[chain]/chart/blocksize/page.tsx, src/app/[chain]/chart/burnt/page.tsx, src/app/[chain]/chart/cycle-count/page.tsx, src/app/[chain]/chart/deployed-contracts/page.tsx, src/app/[chain]/chart/holders/page.tsx, src/app/[chain]/chart/marketcap/page.tsx, src/app/[chain]/chart/month-address/page.tsx, src/app/[chain]/chart/price/page.tsx, src/app/[chain]/chart/production-rate/page.tsx, src/app/[chain]/chart/staked/page.tsx, src/app/[chain]/chart/supply-growth/page.tsx, src/app/[chain]/chart/transactions/page.tsx, src/app/[chain]/chart/tvl/page.tsx, src/app/[chain]/chart/txfee/page.tsx
=> feat: chart code optimization

src/_hooks/useFetchChartData.ts, src/app/[chain]/chart/active-address/page.tsx, src/app/[chain]/chart/address/page.tsx, src/app/[chain]/chart/avg-duration/page.tsx, src/app/[chain]/chart/avg-txfee/page.tsx, src/app/[chain]/chart/blocksize/page.tsx, src/app/[chain]/chart/burnt/page.tsx, src/app/[chain]/chart/contract-calls/page.tsx, src/app/[chain]/chart/cycle-count/page.tsx, src/app/[chain]/chart/deployed-contracts/page.tsx, src/app/[chain]/chart/holders/page.tsx, src/app/[chain]/chart/marketcap/page.tsx, src/app/[chain]/chart/month-address/page.tsx, src/app/[chain]/chart/price/page.tsx, src/app/[chain]/chart/production-rate/page.tsx, src/app/[chain]/chart/rewards/page.tsx, src/app/[chain]/chart/staked/page.tsx, src/app/[chain]/chart/supply-growth/page.tsx, src/app/[chain]/chart/transactions/page.tsx, src/app/[chain]/chart/tvl/page.tsx, src/app/[chain]/chart/txfee/page.tsx
=> feat: chart code

src/_components/OverviewCard/four.tsx, src/_components/OverviewCard/index.tsx, src/_components/OverviewCard/three.tsx, src/_components/OverviewCard/useRenderItem.tsx, src/_pluginsComponents/nft/_transfers/Table.tsx, src/_pluginsComponents/nftItem/_holders/HoldersTable.tsx, src/_utils/formatter.ts, src/app/[chain]/chart/active-address/page.tsx, src/app/[chain]/chart/address/page.tsx, src/app/[chain]/chart/avg-duration/page.tsx, src/app/[chain]/chart/avg-txfee/page.tsx, src/app/[chain]/chart/blocksize/page.tsx, src/app/[chain]/chart/burnt/page.tsx, src/app/[chain]/chart/contract-calls/page.tsx, src/app/[chain]/chart/cycle-count/page.tsx, src/app/[chain]/chart/deployed-contracts/page.tsx, src/app/[chain]/chart/holders/page.tsx, src/app/[chain]/chart/marketcap/page.tsx, src/app/[chain]/chart/month-address/page.tsx, src/app/[chain]/chart/price/page.tsx, src/app/[chain]/chart/production-rate/page.tsx, src/app/[chain]/chart/rewards/page.tsx, src/app/[chain]/chart/staked/page.tsx, src/app/[chain]/chart/supply-growth/page.tsx, src/app/[chain]/chart/transactions/page.tsx, src/app/[chain]/chart/tvl/page.tsx, src/app/[chain]/chart/txfee/page.tsx, src/app/[chain]/tokens/tokensList.tsx
=> feat: code

src/_components/Footer/index.tsx
=> feat: link use https

src/_components/ChainSelect/index.tsx, src/_components/HeaderTop/index.tsx, src/_components/MobileHeaderMenu/index.tsx, src/_hooks/useChainSelect.ts
=> feat: chain select

src/_components/AddressDetail/components/Tokens/NFTAssets/columnConfig.tsx
=> fix nft asset Collection jump

src/app/[chain]/block/[hash]/_components/baseinfo.tsx
=> fix: fix block detail time

src/_components/AddressWithCopy/index.tsx, src/app/[chain]/token/[tokenSymbol]/_components/Transfers/index.tsx, src/app/[chain]/token/[tokenSymbol]/_components/Transfers/utils.tsx
=> fix: fix transfers search

src/app/[chain]/token/[tokenSymbol]/_components/Overview/index.tsx, src/app/[chain]/token/[tokenSymbol]/type.ts
=> feat: change token detail CONTRACT

src/_components/LogsContainer/index.tsx, src/_pluginsComponents/nft/_overview/OverView.tsx, src/_pluginsComponents/nft/type.ts, src/_types/common.ts
=> feat: change nft detail CONTRACT

src/_api/type.ts
=> fix: fix nft type

src/app/[chain]/token/[tokenSymbol]/_components/Transfers/columns.tsx
=> feat: token show contract address

src/_components/AddressDetail/components/Events/index.tsx
=> feat: blockNo only support number

src/app/[chain]/blocks/blockList.tsx
=> fix: fix block last page

src/_components/AddressDetail/components/Tokens/NFTAssets/columnConfig.tsx, src/_components/AddressDetail/components/Tokens/NFTAssets/index.tsx
=> fix: fix address detail nfts sort

src/app/[chain]/chart/produce/page.tsx
=> fix: fix producers

src/app/[chain]/chart/address/page.tsx
=> fix: fix address chart

src/_components/AddressDetail/components/Events/index.tsx, src/_components/AddressDetail/index.tsx, src/_components/BasicTag/index.tsx, src/_components/ChainTags/index.tsx, src/_components/HeaderTitle/index.tsx, src/_pluginsComponents/nft/_holders/column.tsx, src/_pluginsComponents/nft/_overview/OverView.tsx, src/_pluginsComponents/nftItem/_holders/column.tsx, src/_socket/index.ts, src/app/[chain]/chart/active-address/page.tsx, src/app/[chain]/chart/address/page.tsx, src/app/[chain]/chart/avg-txfee/page.tsx, src/app/[chain]/chart/blocksize/page.tsx, src/app/[chain]/chart/burnt/page.tsx, src/app/[chain]/chart/contract-calls/page.tsx, src/app/[chain]/chart/deployed-contracts/page.tsx, src/app/[chain]/chart/holders/page.tsx, src/app/[chain]/chart/month-address/page.tsx, src/app/[chain]/chart/supply-growth/page.tsx, src/app/[chain]/chart/transactions/page.tsx, src/app/[chain]/chart/txfee/page.tsx, src/app/[chain]/nfts/columnConfig.tsx, src/app/[chain]/token/[tokenSymbol]/_components/Holders/columns.tsx, src/app/[chain]/token/[tokenSymbol]/_components/Overview/index.tsx, src/app/[chain]/tokens/columnConfig.tsx, src/pageComponents/home/_components/InfoSection/index.tsx, src/pageComponents/home/index.css, src/pageComponents/home/page.tsx
Chain name modification. close #350
=> feat: chain name modification

src/_api/server.ts, src/_components/AddressDetail/components/Contract/index.tsx, src/_components/AddressDetail/components/Contract/sourceCode.tsx, src/_components/AddressDetail/components/DynamicForm/formItem.tsx, src/_components/AddressDetail/components/DynamicForm/index.tsx, src/_components/AddressDetail/components/DynamicForm/valueFormItem.tsx, src/_components/AddressDetail/components/FileTree/index.tsx, src/_components/CodeViewer/index.tsx, src/_components/EPTabs/index.tsx, src/_components/HeaderMenu/index.tsx, src/_components/Search/SearchBox.tsx, src/_graphql/client.ts, src/_hooks/useBlockchainOverview.ts, src/_hooks/useBpProduce.ts, src/_hooks/useHomeSocket.ts, src/_hooks/useSearchFilters.ts, src/_hooks/useTable.ts, src/_hooks/useUpdateQueryParams.ts, src/_pluginsComponents/nft/CollectionDetails.tsx, src/_socket/index.ts, src/_socket/signalr.ts, src/_utils/ad.ts, src/_utils/deserializeLog.ts, src/_utils/urlUtils.ts, src/app/[chain]/source-code/[address]/code.tsx, src/app/opentelemetryProvider.tsx, src/app/pluginsPage/page.tsx
=> feat: upload rules

global.d.ts, src/_api/fetchContact.ts, src/app/[chain]/source-code/[address]/code.tsx
=> feat: add errCode

src/app/[chain]/source-code/[address]/code.tsx
=> feat: catch error

src/_hooks/useSearch.ts
=> fix: fix search chain

src/_components/ChainSelect/index.css, src/_components/ContractToken/index.tsx, src/_components/Footer/index.tsx, src/_components/HeaderMenu/index.css, src/_components/Table/index.css, src/_style/globals.css, src/app/[chain]/transactions/columnConfig.tsx
=> feat: change img

src/_components/ChainSelect/index.css
=> feat: select center

package.json, src/_api/fetchCMS.ts, src/_api/list.ts, src/_components/NetWorkSwitch/index.css, src/_components/NetWorkSwitch/index.tsx, src/pageComponents/home/_components/ScrollAds/index.tsx, src/pageComponents/home/_components/ScrollTwitter/index.tsx, src/pageComponents/home/index.css, src/pageComponents/home/page.tsx, yarn.lock
=> feat: home style done

src/_api/fetchCMS.ts, src/_api/list.ts, src/_components/ChainTags/index.tsx, src/_components/DetailContainer/index.tsx, src/_components/DollarCurrencyRate/index.tsx, src/_components/EPTabs/index.css, src/_components/IconFont/index.tsx, src/_components/LogsContainer/index.tsx, src/_components/LogsContainer/logItem.css, src/_components/LogsContainer/logItems.tsx, src/_components/Main/index.css, src/_components/TokenTableCell/index.tsx, src/_components/TransactionsStatus/index.tsx, src/_components/TransactionsView/index.tsx, src/app/[chain]/nfts/columnConfig.tsx, src/app/[chain]/nfts/list.tsx, src/app/[chain]/nfts/page.tsx, src/app/[chain]/tokens/_components/TokenImage/index.tsx, src/app/[chain]/tokens/columnConfig.tsx, src/app/[chain]/tokens/page.tsx, src/app/[chain]/tokens/tokensList.tsx, src/app/[chain]/transactions/columnConfig.tsx, src/app/[chain]/tx/[hash]/_components/ExtensionInfo.tsx, src/app/[chain]/tx/[hash]/_components/baseInfo.tsx, src/app/[chain]/tx/[hash]/_components/detail.tsx, src/pageComponents/home/_components/ScrollAds/index.tsx
=> feat: nfts tokens and txdetail

src/_components/HeaderTop/index.tsx, src/_components/IconFont/index.tsx, src/app/[chain]/nfts/columnConfig.tsx, src/app/[chain]/nfts/list.tsx, src/pageComponents/home/_components/Latest/index.css
=> feat: nft add #

src/_components/AddressDetail/components/Tokens/TokenValue/index.tsx, src/_components/ContractToken/multiChain.tsx, src/_components/ContractToken/qrCode.tsx
=> feat: address detail add qrcode

src/_components/AddressDetail/components/Events/columnConfig.tsx, src/_components/LogsContainer/index.tsx, src/_components/LogsContainer/logItems.tsx
=> feat: address logs

src/_components/AddressDetail/components/Tokens/TokenValue/index.tsx
=> feat: token value add $

src/_components/AddressDetail/components/DynamicForm/index.tsx, src/_components/AddressDetail/index.tsx, src/_components/EPSortIcon/index.tsx, src/_components/Search/Item.tsx, src/_components/Search/Panel.tsx, src/_components/Search/SearchBox.tsx, src/_components/Search/type.ts, src/_hooks/useSearch.ts, src/_utils/formatter.ts
=> fix: fix search jump clear

src/_components/IconFont/index.tsx
=> feat: change help icon

src/_api/type.ts, src/_components/AddressDetail/components/Contract/code.css, src/_components/AddressDetail/components/Contract/sourceCode.tsx, src/_components/AddressDetail/components/DynamicForm/index.tsx, src/_components/AddressDetail/components/Tokens/List/index.tsx, src/_components/AddressDetail/components/Tokens/TokenValue/index.tsx, src/_components/CodeBlock/index.css, src/_components/Copy/index.tsx, src/_components/HeaderMenu/memuItem.tsx, src/_components/HeaderTitle/index.tsx, src/_utils/copy.ts, src/pageComponents/home/_components/Latest/index.css, src/pageComponents/home/_components/Latest/index.tsx, tailwind.config.js
=> fix: fix font wight

src/_api/server.ts, src/_components/EPToolTip/index.css, src/_components/EPToolTip/index.tsx, src/_components/HeaderMenu/index.css, src/_components/MobileHeaderMenu/index.css, src/pageComponents/home/_components/Banner.tsx, src/pageComponents/home/index.css
=> fix: fix tooltip style

src/_components/AddressDetail/AddressContext.tsx, src/_components/AddressDetail/components/Events/index.css, src/_components/AddressDetail/components/Events/index.tsx, src/_components/AddressDetail/components/Tokens/List/index.tsx, src/_components/AddressDetail/components/Tokens/NFTAssets/columnConfig.tsx, src/_components/AddressDetail/components/Tokens/NFTAssets/index.tsx, src/_components/AddressDetail/components/Tokens/index.tsx, src/_components/AddressDetail/index.tsx, src/_components/ChainSelect/index.css, src/_components/ChainSelect/multiCain.tsx, src/_components/ContractToken/index.tsx, src/_components/IconFont/index.tsx, src/_components/NFTTransfers/index.tsx, src/_components/Search/Item.tsx, src/_components/Search/Panel.tsx, src/_components/Search/SearchBox.tsx, src/_components/TokenTransfers/columnConfig.tsx, src/_components/TokenTransfers/index.tsx, src/_style/not-found.css, src/_style/search.css, src/_utils/contant.ts, src/app/[chain]/address/[address]/page.tsx, src/app/[chain]/chart/_components/index.css, src/app/[chain]/transactions/aaList.tsx, src/app/[chain]/transactions/columnConfig.tsx, src/app/[chain]/transactions/list.tsx, src/app/[chain]/transactions/page.tsx, src/app/error.tsx, src/pageComponents/home/_components/Latest/index.tsx, tailwind.config.js
=> fix: fix style

src/_components/NetWorkSwitch/index.tsx, src/pageComponents/home/_components/Latest/index.css
=> fix: fix network switch

src/_api/server.ts, src/_components/HeaderTop/price.tsx, src/_style/globals.css, src/pageComponents/home/_components/Banner.tsx
=> differentiate testnet

src/_api/server.ts, src/_components/HeaderTop/price.tsx, src/_socket/index.ts, src/app/[chain]/contracts/columnConfig.tsx, src/pageComponents/home/_components/Banner.tsx
=>  differentiate testnet

src/_utils/urlUtils.ts
=> fix: fix download

src/_components/ContractToken/multiChain.tsx, src/_components/Footer/index.tsx, src/_components/TokenTransfers/index.tsx, src/app/[chain]/chart/production-rate/page.tsx, src/app/[chain]/contracts/contractsList.tsx
=> fix: fix dropdown

src/pageComponents/home/_components/InfoSection/index.tsx
=> chore: correct spelling mistake
